version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: book_dictionary_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_dictionary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    restart: unless-stopped

volumes:
  postgres_data:
